In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)

In [15]:
slice_of_array = arr[0:6]

In [17]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
#slicing points to same reference in memory - use copy()
arr_copy = arr.copy()

In [20]:
arr_copy[:] = 100

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])